Repository fortanix/baklava, pull requests merged in 2025-08, with the labels that each got.

#452 Release v1.0.0-beta-20250808
  package-lock.json
  package.json
  package.json.js
Labels: release

#458 (#404) Use aria-current=step in Stepper component
  src/components/navigations/Stepper/Stepper.module.scss
  src/components/navigations/Stepper/Stepper.tsx
Labels: a11y

#456 (#402) Add role=switch in Switch component
  src/components/forms/controls/Switch/Switch.tsx
Labels: a11y

#459 (#406) Add aria-sort to a sorted column in DataTable
  src/components/tables/DataTable/table/DataTable.tsx
Labels: a11y

#460 (#377) Make the DataTable sortable via keyboard
  src/components/tables/DataTable/table/DataTable.tsx
Labels: a11y, tables

#470 Release v1.0.0-beta-20250828
  package-lock.json
  package.json
  package.json.js
Labels: release
